# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PreferenceModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PreferenceModule

  # NebulaCore
  pod 'NebulaCore2', :git => 'https://www.t5online.com:8002/t5-frameworks/nebula.git'

end
